Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using FinalProject.Models;
using FinalProject.Data;
using System.Net.Mail;

namespace FinalProject.Controllers
{
    public class OrderController : Controller
    {
        private readonly ApplicationDbContext _context;
        public OrderController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            var list = _context.Orders.ToList();
            return View(list);
        }
        public IActionResult Create()
        {
            return View();
        }
       
        [HttpPost]
        public IActionResult Create(Order record)
        {
            var order = new Order();
            order.ProductName = record.ProductName;
            order.Price = record.Price;
            order.Quantity = record.Quantity;
            order.Address = record.Address;
            order.ContactNum = record.ContactNum;
            order.DateAdded = DateTime.Now;
            order.ModeOfPayment = record.ModeOfPayment;

            _context.Orders.Add(order);
            _context.SaveChanges();

            return RedirectToAction("Index");

        }
       
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            var order = _context.Orders.Where(i => i.OrderID == id).SingleOrDefault();
            if (order == null)
            {
                return RedirectToAction("Index");
            }
            _context.Orders.Remove(order);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }
        public IActionResult Track()
        {
            return View();
        }
    }
}

Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using FinalProject.Models;
using FinalProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace FinalProject.Controllers
{
    public class ProductController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProductController(ApplicationDbContext context)
        {
            _context = context;
            
        }
        public IActionResult Index()
        {

            var list = _context.Items.ToList();
            return View(list);

        }


        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Item record, IFormFile ImagePath)
        {            
            var product = new Item();
            product.ProductName = record.ProductName;
            product.ProductCode = record.ProductCode;
            product.ProductDescription = record.ProductDescription;
            product.ProductPrice = record.ProductPrice;
            product.Available = record.Available;
            product.DateAdded = DateTime.Now;
            product.Categories = record.Categories;

            if (ImagePath != null)
            {
                if (ImagePath.Length > 0)
                {
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(),
                        "wwwroot/images/products", ImagePath.FileName);

                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        ImagePath.CopyTo(stream);
                    }
                    product.ImagePath = ImagePath.FileName;
                }
            }
            _context.Items.Add(product);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            
            var product = _context.Items.Where(p => p.ProductID == id).SingleOrDefault();
            if (product == null)
            {
                return RedirectToAction("Index");
            }

            return View(product);
        }

        [HttpPost]
        public IActionResult Edit(int? id, Item record, IFormFile ImagePath)
        {
            var product = _context.Items.Where(p => p.ProductID == id).SingleOrDefault();

            product.ProductName = record.ProductName;
            product.ProductCode = record.ProductCode;
            product.ProductDescription = record.ProductDescription;
            product.ProductPrice = record.ProductPrice;
            product.Available = record.Available;
            product.Categories = record.Categories;
            if (ImagePath != null)
            {
                if (ImagePath.Length > 0)
                {
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(),
                        "wwwroot/images/products", ImagePath.FileName);

                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        ImagePath.CopyTo(stream);
                    }
                    product.ImagePath = ImagePath.FileName;
                }
            }


            _context.Items.Update(product);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }

            var product = _context.Items.Where(p => p.ProductID == id).SingleOrDefault();
            if (product == null)
            {
                return RedirectToAction("Index");
            }

            _context.Items.Remove(product);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

    }
}

Controllers/StoreController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FinalProject.Models;
using FinalProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace FinalProject.Controllers
{
    public class StoreController : Controller
    {
        private readonly ILogger<StoreController> _logger;
        private readonly ApplicationDbContext _context;

        public StoreController(ILogger<StoreController> logger, ApplicationDbContext context)
        {
            _logger = logger;
            _context = context;
        }
        public IActionResult Index()
        {
            var products = _context.Items.ToList();
            if (Request.Query.ContainsKey("card"))
            {
                Categories cat = (Categories)int.Parse(Request.Query["card"].ToString());
                products = products.Where(p => p.Categories == cat).ToList();
            }
            var record = new StoreViewModel()
            {
                ProductList = products
            };
            return View(record);
        }
        public IActionResult Earphones()
        {
            var products = _context.Items.Where(i => i.Categories == Categories.Earphones).ToList();
            var record = new StoreViewModel()
            {
                ProductList = products
            };
            return View(record);
        }
        public IActionResult Macbook()
        {
            var products = _context.Items.Where(i => i.Categories == Categories.Macbooks).ToList();
            var record = new StoreViewModel()
            {
                ProductList = products
            };
            return View(record);
        }
        public IActionResult Iphones()
        {
            var products = _context.Items.Where(i => i.Categories == Categories.Iphones).ToList();
            var record = new StoreViewModel()
            {
                ProductList = products
            };
            return View(record);
        }
        public IActionResult Watch()
        {
            var products = _context.Items.Where(i => i.Categories == Categories.AppleWatch).ToList();
            var record = new StoreViewModel()
            {
                ProductList = products
            };
            return View(record);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FinalProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/custom.css" />
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">iStore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Store" asp-action="Index"><i class="fas fa-shopping-bag"></i></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy"><i class="fas fa-info-circle"></i></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Contactus">
                                <i class="fas fa-phone"></i></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Order" asp-action="Create"><i class="fas fa-shopping-cart"></i></a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021  All Rights Reserved - ISTORE - <a asp-area="" asp-controller="Product" asp-action="Index">Products Index</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>